# Generated by Django 2.2.2 on 2019-06-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplclone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='match_id',
            new_name='match',
        ),
    ]
